
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: lhb64961077
    url: jdbc:mysql://localhost:3306/jwtdemo2?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
